# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker-compose up -d --build \
    command: echo 'Composing the project Docker'
  - init: cd portal \
    command: echo 'Move to Portal directory'
  - init: npm run dev
    command: echo 'Starting the Server'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
