name: CI/CD check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
defaults:
  run:
    working-directory: portal

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run eslint test
      run: yarn lint
      
    - name: Build
      run: yarn build
